/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ff;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author ficarra.gabriele
 */
public class SchermataIniziale extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SchermataIniziale.class.getName());
    private JButton btnNuova, btnCarica, btnClassifica;

    /**
    class PannelloSfondo extends JPanel { // ho scritto una classe interna al form per non farla esterna

        Image immagine;
        
        PannelloSfondo() {
            immagine = new ImageIcon(getClass().getResource("/ff/immagini/schermata.png")).getImage();
        }
        
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            g.drawImage(immagine, 0, 0, getWidth(), getHeight(), this);
        }
    }

    public SchermataIniziale() {
        initComponents();

        pnlSchermata = new PannelloSfondo();
        pnlSchermata.setLayout(null); //sennò non mi fa mettere i bottoni
        this.setContentPane(pnlSchermata);

        creaInterfaccia();

        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                int nuovaX = (getWidth() / 2) + 100;
                int nuovaY = (getHeight() / 2) + 45;

                btnNuova.setLocation(nuovaX, nuovaY);
                btnCarica.setLocation(nuovaX + 15, nuovaY + 35);
                btnClassifica.setLocation(nuovaX + 30, nuovaY + 70);
            }
        });

        this.setLocationRelativeTo(null);
    }

    private void creaInterfaccia() {
        btnNuova = creaBottoneSottile("NEW GAME");
        btnCarica = creaBottoneSottile("LOAD GAME");
        btnClassifica = creaBottoneSottile("LEADERBOARD");

        btnNuova.addActionListener(e -> {
            this.dispose();
            new PartitaVisual().setVisible(true);
        });

        btnCarica.addActionListener(e -> caricaPartitaEsistente());

        pnlSchermata.add(btnNuova);
        pnlSchermata.add(btnCarica);
        pnlSchermata.add(btnClassifica);
    }

    private JButton creaBottoneSottile(String testo) { // così riesco a dare l'effetto a "scala" dell'originale
        JButton b = new JButton(testo);
        b.setSize(300, 25);

        b.setContentAreaFilled(false); // volevo renderlo come nell'originale
        b.setBorderPainted(false);
        b.setFocusPainted(false);
        b.setForeground(Color.WHITE);
        b.setFont(new Font("SansSerif", Font.PLAIN, 14));
        b.setHorizontalAlignment(SwingConstants.LEFT);

        b.addMouseListener(new MouseAdapter() { // volevo simulare l'effetto azzurro di FFXV
            
            public void mouseEntered(MouseEvent e) {
                b.setForeground(new Color(173, 216, 230));
                b.setText(">  " + testo); // Simula la freccia dell'origniale
            }

            public void mouseExited(MouseEvent e) {
                b.setForeground(Color.WHITE);
                b.setText(testo);
            }
        });
        return b;
    }

    private void caricaPartitaEsistente() {
        if (FileManager.caricaCSV()) {
            this.dispose();
            new PartitaVisual().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Salvataggio non trovato!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSchermata = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout pnlSchermataLayout = new javax.swing.GroupLayout(pnlSchermata);
        pnlSchermata.setLayout(pnlSchermataLayout);
        pnlSchermataLayout.setHorizontalGroup(
            pnlSchermataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        pnlSchermataLayout.setVerticalGroup(
            pnlSchermataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(pnlSchermata, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SchermataIniziale().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlSchermata;
    // End of variables declaration//GEN-END:variables
}
